### PR TITLE
FreeBSD support

### PR DESCRIPTION
**Pull request by tycho**
A bunch of changes to make the project build and run on FreeBSD.

### CODE REVIEW

**Comment by preshing** [comment]
Was /proc/cpuinfo recently added to FreeBSD or something? [This SO answer](http://stackoverflow.com/a/4088577/3043469) and other Google hits suggest /proc/cpuinfo is not available on FreeBSD.

**Comment by tycho** [comment]
There's one in linprocfs, but it's not great.

I'll implement the more FreeBSD-ish approach of using sysctls...

**Comment by tycho** [comment]
Also in my own projects I avoid reading /proc/cpuinfo for this exact reason -- it's not portable. It's far better to iterate through the full set of CPU indexes by trying to bind to CPU 0, then 1, then 2... etc until you hit an error condition. See here for example:

https://github.com/tycho/cpuid/blob/master/threads.c#L62

**Comment by tycho** [comment]
And to find the Package/Core/Thread indexes you can use the APIC ID:

https://github.com/tycho/cpuid/blob/master/handlers.c#L725

**Comment by tycho** [comment]
Implemented physical/core detection via CPUID.

Do any of the tests actually exercise that in a meaningful way? All the examples ran without complaints even while the /proc/cpuinfo bit was obviously completely broken (since it didn't even exist)...

**Comment by preshing** [comment]
I use it to automatically determine how many threads to spawn, with one per core (no hyperthreading), when benchmarking. I found the results more consistent that way.

**Comment by tycho** [comment]
Yeah, that's fair. If that's all you want, you could just check if the APIC ID is even or odd. Even is front-half hyperthread, Odd is back-half.

**Pull request merged**
